// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPtnQTcPfGUSKnjDIBhdXzfMFAHq1ipjQ',
    appId: '1:354048220850:web:f354ab456b628a71edb3ab',
    messagingSenderId: '354048220850',
    projectId: 'safeerv3-f59a4',
    authDomain: 'safeerv3-f59a4.firebaseapp.com',
    storageBucket: 'safeerv3-f59a4.appspot.com',
    measurementId: 'G-0GC3CF9Y2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk9JkB7fUCsgQKBLLmJ_f33D5Z_CzpnVs',
    appId: '1:354048220850:android:682663556c5c021cedb3ab',
    messagingSenderId: '354048220850',
    projectId: 'safeerv3-f59a4',
    storageBucket: 'safeerv3-f59a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDgjpgmmQZTXDxMQHCjgjrCnJXbfynz20',
    appId: '1:354048220850:ios:0fa8c164850c469dedb3ab',
    messagingSenderId: '354048220850',
    projectId: 'safeerv3-f59a4',
    storageBucket: 'safeerv3-f59a4.appspot.com',
    iosBundleId: 'com.example.safeer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDgjpgmmQZTXDxMQHCjgjrCnJXbfynz20',
    appId: '1:354048220850:ios:62b7d0f858a47da6edb3ab',
    messagingSenderId: '354048220850',
    projectId: 'safeerv3-f59a4',
    storageBucket: 'safeerv3-f59a4.appspot.com',
    iosBundleId: 'com.example.safeer.RunnerTests',
  );
}
